FROM node:22
WORKDIR /usr/src/app
COPY package*.json webpack* ./
RUN rm -rf ./node_modules
RUN rm ./package-lock.json
RUN npm cache clean --force
RUN npm install -g webpack webpack-cli
RUN echo "Force reinstall"
RUN npm install --force
COPY src ./src
