FROM node:22
RUN apt-get update && apt-get install -y gettext-base
WORKDIR /usr/src/app
COPY package*.json webpack* ./
RUN npm install -g webpack webpack-cli
RUN echo "Force reinstall"
RUN npm install --force
COPY src ./src
