#!/usr/bin/env bash
#
# gen-certs.sh — one-time generation of the SAML signing/encryption keypairs
# for the IdP and the two SPs (these are SAML credentials, NOT the nginx-proxy
# TLS certs — those come from gen-tls-local.sh or acme-companion).
#
# It then:
#   * writes the static htpasswd file holding the single demo account, and
#   * stashes the base64 certificate bodies in scripts/.certs-env.sh and runs
#     render.sh so the bodies land inside the three XML EntityDescriptors.
#
# Safe to re-run: pass --force to regenerate keypairs (otherwise existing ones
# are kept and only the templates / htpasswd are refreshed).

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
FORCE=0
[ "${1:-}" = "--force" ] && FORCE=1

if [ ! -f "$ROOT/.env" ]; then
    echo "ERROR: $ROOT/.env not found. Copy .env.example to .env first." >&2
    exit 1
fi
set -a; source "$ROOT/.env"; set +a

DAYS=3650

# gen_keypair <dir> <basename> <subject-CN>
gen_keypair() {
    local dir="$1" base="$2" cn="$3"
    mkdir -p "$dir"
    if [ "$FORCE" -eq 0 ] && [ -f "$dir/$base.crt" ] && [ -f "$dir/$base.key" ]; then
        echo "  keep   $base (exists; --force to regenerate)"
        return
    fi
    openssl req -x509 -nodes -newkey rsa:3072 \
        -keyout "$dir/$base.key" -out "$dir/$base.crt" \
        -days "$DAYS" -subj "/CN=$cn" >/dev/null 2>&1
    chmod 644 "$dir/$base.crt"; chmod 640 "$dir/$base.key"
    echo "  wrote  $base ($cn)"
}

cert_body() { # strip PEM armor + newlines -> single-line base64 for XML
    sed -e '/-----BEGIN/d' -e '/-----END/d' "$1" | tr -d '\n\r'
}

echo "Generating SAML keypairs..."
gen_keypair "$ROOT/idp/config/credentials"  idp-signing    "$IDP_HOST signing"
gen_keypair "$ROOT/idp/config/credentials"  idp-encryption "$IDP_HOST encryption"
gen_keypair "$ROOT/idp2/config/credentials" idp-signing    "$IDP2_HOST signing"
gen_keypair "$ROOT/idp2/config/credentials" idp-encryption "$IDP2_HOST encryption"
gen_keypair "$ROOT/sp1/credentials"        sp-signing     "$SP1_HOST signing"
gen_keypair "$ROOT/sp1/credentials"        sp-encryption  "$SP1_HOST encryption"
gen_keypair "$ROOT/sp2/credentials"        sp-signing     "$SP2_HOST signing"
gen_keypair "$ROOT/sp2/credentials"        sp-encryption  "$SP2_HOST encryption"

echo "Writing demo-account htpasswd files..."
# Shibboleth's HTPasswdValidator delegates hash verification to Apache Commons
# Codec Crypt, which supports crypt(3) families $1$ (MD5), $5$ (SHA-256) and
# $6$ (SHA-512) — but NOT bcrypt ($2a$/$2y$), which fails with
# "Invalid salt value". So use SHA-512 crypt ($6$), generated by openssl.
HT="$ROOT/idp/config/credentials/idp.htpasswd"
printf '%s:%s\n' "$DEMO_USER" "$(openssl passwd -6 "$DEMO_PASS")" > "$HT"
chmod 640 "$HT"
echo "  wrote  idp/...  idp.htpasswd ($DEMO_USER)"

HT2="$ROOT/idp2/config/credentials/idp.htpasswd"
printf '%s:%s\n' "$DEMO2_USER" "$(openssl passwd -6 "$DEMO2_PASS")" > "$HT2"
chmod 640 "$HT2"
echo "  wrote  idp2/... idp.htpasswd ($DEMO2_USER)"

echo "Stashing certificate bodies for template rendering..."
cat > "$HERE/.certs-env.sh" <<EOF
# Generated by gen-certs.sh — base64 X509 bodies for the XML descriptors.
export IDP_SIGNING_CERT='$(cert_body "$ROOT/idp/config/credentials/idp-signing.crt")'
export IDP_ENCRYPTION_CERT='$(cert_body "$ROOT/idp/config/credentials/idp-encryption.crt")'
export IDP2_SIGNING_CERT='$(cert_body "$ROOT/idp2/config/credentials/idp-signing.crt")'
export IDP2_ENCRYPTION_CERT='$(cert_body "$ROOT/idp2/config/credentials/idp-encryption.crt")'
export SP1_SIGNING_CERT='$(cert_body "$ROOT/sp1/credentials/sp-signing.crt")'
export SP1_ENCRYPTION_CERT='$(cert_body "$ROOT/sp1/credentials/sp-encryption.crt")'
export SP2_SIGNING_CERT='$(cert_body "$ROOT/sp2/credentials/sp-signing.crt")'
export SP2_ENCRYPTION_CERT='$(cert_body "$ROOT/sp2/credentials/sp-encryption.crt")'
EOF
chmod 600 "$HERE/.certs-env.sh"

echo "Rendering templates with embedded certs..."
bash "$HERE/render.sh"

echo "gen-certs.sh: done."
